### ISSUE TITLE
Show underlying form in glossing?

### ISSUE THREAD

**Issue by fmatter** [timarkh/uniparser-morph#1]
Just wondering: how difficult would it be to implement a functionality where the "underlying" or "full" form of a morpheme is shown in interlinear glossing? So one could get something like this:

*wonse*
womï-se
enter-PST
'entered'

(Yawarana *womï* undergoes the regular process of syllable reduction, yielding *won* in certain forms).

**Comment by timarkh** [comment]
Good idea! I'm working on it.

**Comment by timarkh** [comment]
I guess I implemented what you wanted, see details here: https://uniparser-morph.readthedocs.io/en/latest/format.html#standardized-underlying-form-of-morphemes . Could you maybe test if it works as intended before I release a new version?

**Comment by fmatter** [comment]
Will try tomorrow!

**Comment by fmatter** [comment]
Put together a MWE: [uniparser-mwe.zip](https://github.com/timarkh/uniparser-morph/files/8223266/uniparser-mwe.zip); the idea being that *wonse* is underlyingly *womï-che* (disclaimer: not actually true).

The analyzed wordform has `womï` as its `std` value; *-che* is nowhere to be seen. From what I can glean from the documentation, I would expect this:

`wf`: wonse
`wfGlossed`: won-se
`wfGlossedStd`: womï-che
`gloss`: enter-PST

**Comment by fmatter** [comment]
I've just tried it again and it is in fact working even without the period. I think I may have been using the wrong version when I built the MWE 🤦. This does exactly what I was thinking of, thanks for the incredibly quick work!

**Comment by timarkh** [comment]
Perfect!
